######## Scheduler Configuration ########

# data store configuration
data_store:
  type: sqlalchemy
  url: "postgresql+asyncpg://edge:edge@db/flowerpower"

# event broker configuration
event_broker:
  type: asyncpg
  url: "postgresql+asyncpg://edge:edge@db/flowerpower"


pipeline:
  my_flow:
    type: cron
    crontab: "* * * * *"
    # start_time:
    # end_time:
    # timezone:
    # cron arguments
    # year:
    # month:
    # week:
    # day:
    # days_of_week:
    # hour:
    # minute:
    # second:
    # interval arguments
    # weeks:
    # days:
    # hours:
    # minutes:
    # seconds:
    # microseconds:
    


## Configuration options ## 

# sqlite data store
# data_store:
#   type: sqlalchemy
#   url: "sqlite+aiosqlite:///flowerpower.db"

# memory data store
# data_store:
#   type: lccal # or memory

# mongodb data store
# data_store:
#   type: mongodb
#   url: "mongodb://localhost:27017/scheduler"

# mqtt event broker
# event_broker:
#   type: mqtt
#   host: localhost
#   port: 1883
#   username: "edge"
#   password: "edge"

# redis event broker
# event_broker:
#   type: redis
#   host: localhost
#   port: 6379

# memory event broker
# event_broker:
#   type: memory
