version: "2"
services:
  jupytercode:
    build: 
      context: .
      args:
        - CODE_VERSION=4.89.1
        - PLATFORM=arm64
    image: jupytercode:latest
    user: root
    environment:
      - GRANT_SUDO=yes
    ports:
      - 8888:8888
    volumes:
      - jupytercode:/home/jovyan

  minio:
    image: minio/minio
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: edge
      MINIO_SECRET_KEY: edge1234
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
  
  mqtt:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    command: mosquitto -c /mosquitto/config/mosquitto.conf

  redis:
    image: valkey/valkey
    ports:
      - 6379:6379
  
  mongodb:
    image: mongo
    ports:
      - 27017:27017

  nodered:
    image: nodered/node-red
    volumes:
      - nodered:/data
    ports: 
      - 1880:1880

  postgres:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=flowerpower
      - POSTGRES_USER=edge
      - POSTGRES_PASSWORD=edge
    ports:
      - 5432:5432
    restart: always

  hamilton_api:
    image: dagworks/ui-backend:latest
    entrypoint: ["/bin/bash", "-c", "cd /code/server && ls && ./entrypoint.sh"]
    ports:
      - 8241:8241
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=flowerpower
      - DB_USER=edge
      - DB_PASSWORD=edge # TODO: Change this to a secret
      - HAMILTON_BLOB_STORE=local
      - HAMILTON_ENV=local # local env
      - HAMILTON_LOCAL_BLOB_DIR=/data/blobs # TODO -- set this up to be a better one
      - DJANGO_SECRET_KEY=do_not_use_in_production
      - HAMILTON_TELEMETRY_ENABLED=false #${HAMILTON_TELEMETRY_ENABLED-true}
      - HAMILTON_AUTH_MODE=permissive
    depends_on:
      - postgres
    volumes:
      - backend_data:/data/

  hamilton_ui:
    image: dagworks/ui-frontend:latest
    ports:
      - 8242:8242
    environment:
      - NODE_ENV=development
      - REACT_APP_AUTH_MODE=local
      - REACT_APP_USE_POSTHOG=false
    depends_on:
      - hamilton_api

volumes:
  jupytercode:
  minio_data:
  minio_config:
  nodered:
  postgres_data:
  backend_data:
